/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunkist_photoboard_MainActivity_PhotoArrayAdapter */

#ifndef _Included_com_sunkist_photoboard_MainActivity_PhotoArrayAdapter
#define _Included_com_sunkist_photoboard_MainActivity_PhotoArrayAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
