/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sunkist_photoboard_MainActivity_LoadTask */

#ifndef _Included_com_sunkist_photoboard_MainActivity_LoadTask
#define _Included_com_sunkist_photoboard_MainActivity_LoadTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
